### ISSUE TITLE
sqrt check?

### ISSUE THREAD

**Issue by leonardoalt** [julesdesmit/grumpkin#5]
I noticed today that this repo changes the halo2curves sqrt test for BN256 from
```rust
CtOption::new(tmp, tmp.square().ct_eq(self))
```
to
```rust
CtOption::new(tmp, !self.ct_eq(&Self::zero()))
```
in https://github.com/jules/grumpkin/blob/main/src/fr.rs#L194.

I noticed it when it started giving me wrong square roots for Fr elements (here BN's Fq), so wondering how that works.

**Comment by jules** [comment]
good catch - not sure how that slipped in, although i'm assuming it happened due to my not keeping up with changes in the halo2curves repo :) i'll go ahead and amend it at the very least
